# Generated by Django 4.1.6 on 2023-02-04 00:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.CharField(max_length=300),
        ),
    ]
